name: Release Extension

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Fetch assets
        run: bun run prep

      - name: Build (Chromium)
        run: bun run build

      - name: Zip (Chromium)
        run: bun run zip

      - name: Build (Firefox)
        run: bun run build:firefox

      - name: Zip (Firefox)
        run: bun run zip:firefox

      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Verify ZIP artifacts
        run: |
          ls -la .output | cat
          NUM_ZIPS=$(ls -1 .output/*.zip 2>/dev/null | wc -l || true)
          if [ "$NUM_ZIPS" -eq 0 ]; then
            echo "Error: No zip artifacts found in .output/"
            exit 1
          fi
          echo "Found zip artifacts:"
          ls -la .output/*.zip | cat

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            .output/*.zip
